### PR TITLE
Update to ember-power-select@4 and Ember Octane/Glimmer Components

### PR DESCRIPTION
**Pull request by ttill**
* Also fixes usage of onInput

Breaking changes
* Following the change in power-select 3, event names are now camelCased
* Use of glimmer components (in case components are subclassed)
* Nested options list used to avoid having to copy code from `power-select/options` could break styling

ToDo
- [x] Update ember-try config (ember-power-select only works on Ember 3.11+)
- [x] Fix tests failures related to ember-infinity (https://github.com/ember-infinity/ember-infinity/pull/426, though not relevant anymore after port to power-select 4 and glimmer components)
- [x] Bring back API docs
- [x] angle-brackets and glimmer components in docs 
- [x] Fix broken and incomplete docs on "global configuration"

### CODE REVIEW

**Comment by nickschot** [comment]
Nice! This is great. I was also working on an upgrade to power-select 4 a while ago (but at that time it was still broken). Just noticed v4 stable was recently released. So what I think we can do best is get this out as v3 first, with a major bump, and then shortly after that also release a major version that is compatible with v4 & Octane (3.13+).

**Comment by ttill** [comment]
Thanks for your feedback. I already did the migration to power-select 4 and octane as it was easier to fix the tests like this.

My changes break the API docs to some extent, as the list of supported arguments was removed from `ModelSelect`. How do you want to proceed on this?

**Comment by ttill** [comment]
Oh, and we'd also need to update the docs to promote using angle-brackets + glimmer components.

**Comment by ttill** [comment]
Finally added/updated docs, so this should be ready for merging from my end.

One thing I noticed (also while using this addon): It is a bit confusing that we use defaults for ember-infinity options (`pageParam`, …) that differ from the defaults of ember-infinity itself. As the changes in this PR require a major version bump anyways, maybe the defaults should also be streamlined with ember-infinity?

**Comment by nickschot** [comment]
@ttill thanks for all the work! I'll review this asap. If I remember correctly the main reason to change those defaults was because they matched my use case at the time (and the first releases did not have global settings). Happy to change it to match defaults though. Does need to be a separate PR so it shows up in the changelog correctly.

**Pull request merged**
